// similar to _app.tsx

import "./globals.css";
import styles from "./layout.module.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Next.js sample app</title>
      </head>
      <body>
        <div className={styles.header}>Root layout file</div>
        <div>{children}</div>
      </body>
    </html>
  );
}
